name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on:
      ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: install
      run: npm install --frozen-lockfile

    - name: build
      run: npm run build

    - name: export
      run: npm run export

    - name: add nojekyll
      run: touch .nojekyll

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
